// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_excavator;
lv_obj_t * ui_Screen1;
lv_obj_t * ui_excavator;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_excavator = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_excavator, &ui_img_546190977);
    lv_obj_set_width(ui_excavator, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_excavator, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_excavator, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_excavator, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_excavator, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_excavator, 120);

    uic_excavator = ui_excavator;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    uic_excavator = NULL;
    ui_excavator = NULL;

}
