// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: RC100

#include "../ui.h"

lv_obj_t * ui_Screen1;
lv_obj_t * ui_ExcavatorImage;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExcavatorImage = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_ExcavatorImage, &ui_img_867962620);
    lv_obj_set_width(ui_ExcavatorImage, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_ExcavatorImage, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_ExcavatorImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ExcavatorImage, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ExcavatorImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ExcavatorImage = NULL;

}
